#ifndef ITEM_NAMES_H
#define ITEM_NAMES_H

enum BlockName {
    DIAMOND,
    IRON,
    REDSTONE,
    STONE,
    DIRT,
    GOLD,
    EMERALD,
    COAL,
    WOOD,
    COBBLESTONE,
    OBSDIAN,

};

enum BlockTexture {
    DIAMOND_TEXTURE,
};

enum BlockTypes {
    DIAMOND_STONE,
    DIAMOND_BLOCK,
};

enum BiomeName {
    BIOME_PLAINS, // PLAINS BIOMES
    BIOME_ICE_PLAINS,
    BIOME_ICE_SPIKE_PLAINS,
    BIOME_FOREST_WDLS, // WOODLANDS
    BIOME_FLOWER_FOREST_WDLS,
    BIOME_BIRCH_FOREST_WDLS,
    BIOME_DARK_FOREST_WDLS,
    BIOME_SNOWY_PLAINS_WDLS,
    BIOME_SPARSE_JUNGLE_WDLS,
    BIOME_TAIGA_WDLS,
    BIOME_FROZEN_PEAKS_MNTS, // MOUNTAIN BIOMES
    BIOME_SNOWY_SLOPES_MNTS
};

#endif