#ifndef ITEM_NAMES_H
#define ITEM_NAMES_H

enum ItemTypes {
    FOOD_TYPE,
    TOOL_TYPE,
    POSION_TYPE,
};

enum ElementType {
    DIAMOND_ELEMENT,
    GOLD_ELEMENT,
    IRON_ELEMENT,
    DEFAULT_ELEMENT
};

enum ItemMake {
    DIAMOND_MAKE,
    GOLD_MAKE,
    IRON_MAKE,
    DEFAULT_MAKE,
    WHEAT_MAKE,
};

enum SpawnItem {
    GENERATED_ITEM,
    CRAFTED_ITEM,
    DROP_ITEM
};

enum FoodItems {
    FOOD_APPLE,
    FOOD_DIAMOND_APPLE,
    FOOD_WHEAT,
    FOOD_POTATO,
    FOOD_FISH,
    FOOD_CHICKEN,
    FOOD_FOOD,
};

enum BiomeVariationTypes {
    BIOME_PLAINS, // PLAINS BIOMES
    BIOME_ICE_PLAINS,
    BIOME_ICE_SPIKE_PLAINS,
    BIOME_FOREST_WDLS, // WOODLANDS
    BIOME_FLOWER_FOREST_WDLS,
    BIOME_BIRCH_FOREST_WDLS,
    BIOME_DARK_FOREST_WDLS,
    BIOME_SNOWY_PLAINS_WDLS,
    BIOME_SPARSE_JUNGLE_WDLS,
    BIOME_TAIGA_WDLS,
    BIOME_JUNGLE_WDLS,
    BIOME_FROZEN_PEAKS_MNTS, // MOUNTAIN BIOMES
    BIOME_SNOWY_SLOPES_MNTS,
    BIOME_WINDSWEPT_HILLS,
};

enum BiomeTypes {
    BIOME_PLAINS_BIOME,
    BIOME_WOODLANDS_BIOME,
};

enum EffectName {
    LIFE_REGEN,
    JUMP_MULTIPLE,
    NO_EFFECT,
};

enum WorldTypeNames {
    SPAWN_WORLD_WORLD,
    NETHER_WORLD_WORLD,
    END_WORLD_WORLD,
};

enum ClimateNames {
    CLIMATE_RAINING,
    CLIMATE_SNOWING,
    CLIMATE_CLOUDY,
    CLIMATE_SUNNY,
};

enum ItemNameEn {
    DIAMOND_BLOCK,
    DEFAULT_ITEM,
    TREE_OAK,
    TREE_SPRUCE,
    TREE_JUNGLE,
    TREE_DEFAULT,
    SPRUCE_TREE_LEAVES,
    JUNGLE_TREE_LEAVES
};

enum MinecraftItemTypes {
    TREE,
    BIOME
};


#endif

//ItemName_; // potato cake, apple
//ItemTexture_; // Stone, Block, gravel
//ItemType_; // Food, Block, Tool